# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e76edaf7394b3c4a0d49a7267cbc90cdca24ccfb15272611994fda02bb88e066d0d07a29b56b0ddeb1e306cb679f1157840ec9e97b5bfd5bb95199bfca10541

test:
  secret_key_base: b84af320bd4124092a83347c05eea34e16a48cd695aa271bc93a474f403dc70fe9266a09a12107a52d08282ae54c09645e953e957a7a1c6b8b5acc6679094304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
